# Generated by Django 5.0.6 on 2024-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendoapp', '0004_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.IntegerField(unique=True),
        ),
    ]
