# Generated by Django 5.0.6 on 2024-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendoapp', '0006_alter_tipoinmueble_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinmueble',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
